version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: bitnami/redis:6.2.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_AOF_ENABLED=no
    networks:
      - app-tier
  go-verification-code:
    depends_on:
      - redis
    build: .
    ports: 
      - '8080:8080'
    networks:
      - app-tier
