version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis-server:
    image: docker.io/bitnami/redis:6.2.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - app-tier
